apiVersion: v1
kind: ServiceAccount
metadata:
  name: autotune-sa
  labels:
    app: autotune-mvp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: autotune-role
  labels:
    app: autotune-mvp
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: autotune-crb
  labels:
    app: autotune-mvp
subjects:
  - kind: ServiceAccount
    name: autotune-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: autotune-role
  apiGroup: rbac.authorization.k8s.io
