{{- if .Values.workloads.overprovisionedCpu.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.workloads.overprovisionedCpu.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.workloads.overprovisionedCpu.name }}
    container-efficiency.io/autotune: "{{ .Values.workloads.overprovisionedCpu.autotune }}"
    container-efficiency.io/tune-cpu: "{{ .Values.workloads.overprovisionedCpu.tuneCpu }}"
    container-efficiency.io/tune-memory: "{{ .Values.workloads.overprovisionedCpu.tuneMemory }}"
    container-efficiency.io/tune-limits: "{{ .Values.workloads.overprovisionedCpu.tuneLimits }}"
spec:
  replicas: {{ .Values.workloads.overprovisionedCpu.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.workloads.overprovisionedCpu.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.workloads.overprovisionedCpu.name }}
    spec:
      containers:
      - name: {{ .Values.workloads.overprovisionedCpu.name }}
        image: {{ .Values.workloads.overprovisionedCpu.image }}
        command: {{ toYaml .Values.workloads.overprovisionedCpu.command | nindent 8 }}
        resources:
          requests:
            cpu: {{ .Values.workloads.overprovisionedCpu.cpuRequest }}
            memory: {{ .Values.workloads.overprovisionedCpu.memRequest }}
          limits:
            cpu: {{ .Values.workloads.overprovisionedCpu.cpuLimit }}
            memory: {{ .Values.workloads.overprovisionedCpu.memLimit }}
{{- end }}
